package xyz.endelith.data.generator.code;

import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;

public interface CodeGenerator {
    default void ensureDirectory(Path directory) throws IllegalStateException {
        Objects.requireNonNull(directory, "directory");
        
        if (Files.isDirectory(directory)) { 
            return; 
        } 

        try {
            Files.createDirectories(directory);
        } catch (IOException e) {
            throw new IllegalStateException(String.format(
                "Failed to create folder for %s", 
                directory, 
                e
            ));
        }
    }

    default void writeFiles(JavaFile... files) {
        Objects.requireNonNull(files, "file");
        Path to = this.outputFolder();
        Objects.requireNonNull(to, "to");
        for (JavaFile javaFile : files) {
            try {
                javaFile.writeTo(to);
            } catch (IOException e) {
                throw new IllegalStateException("Failed to write all the output!", e);
            }
        }
    }

    default CodeBlock generateJavadoc() { 
        return CodeBlock.builder()
                .add("Code autogenerated, do not edit!")
                .build();
    }

    Path outputFolder();

    default void generate() {
        throw new UnsupportedOperationException(String.format(
            "This generator `%s` does not implement the generate method", 
            getClass().getSimpleName())
        );
    }
}
